/*
 * File: app/store/storeLogin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeProduccion.store.storeLogin', {
    extend: 'Ext.data.Store',

    requires: [
        'signeProduccion.model.modelLogin',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    config: {
        autoSave: false,
        listeners: {
            write: function(store, operation, eOpts){
        
        if (operation.action == 'destroy') {
        	Ext.MessageBox.show({
        	title: 'Mensaje del Sistema  ',
        	msg:  operation._resultSet.message,
        	buttons: Ext.MessageBox.OK,
        	icon: Ext.MessageBox.INFO
        	});    
        }
        
        if (operation.action == 'create') {
        	Ext.MessageBox.show({
        	title: 'Mensaje del Sistema  ',
        	msg:  operation._resultSet.message,
        	buttons: Ext.MessageBox.OK,
        	icon: Ext.MessageBox.INFO
        	});    
        }
        
        
        if (operation.action == 'update') {
        	Ext.MessageBox.show({
        	title: 'Mensaje del Sistema  ',
        	msg:  operation._resultSet.message,
        	buttons: Ext.MessageBox.OK,
        	icon: Ext.MessageBox.INFO
        	});    
        }        
        	this.load();
        /*this.load({
        	metodo: 'READ',
        	id: 0
        });*/
        }
        }
    },

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeLogin',
            autoLoad: false,
            autoSync: true,
            model: 'signeProduccion.model.modelLogin',
            proxy: {
                type: 'rest',
                api: {
                    read: 'http://localhost/api.signesoft/produccion/iniciarSesion'/*,create: './app/data/ejercicio/CreateEjercicio.php',
                    update: './app/data/ejercicio/UpdateEjercicio.php',
                    destroy: './app/data/ejercicio/DestroyEjercicio.php'*/
                },
                url: '',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    encode: true,
                    rootProperty: 'data'
                },
                listeners: {
                    exception: {
                        fn: me.onAjaxException,
                        scope: me
                    }
                }
            }
        }, cfg)]);
    },

    onAjaxException: function(proxy, request, operation, eOpts) {
        if (operation.getError()){
        	if (operation.getError().statusText){
        		Ext.MessageBox.show({
        			title: 'Mensaje del Sistema',
        			msg: operation.getError().statusText,
        			icon: Ext.MessageBox.ERROR,
        			buttons: Ext.Msg.OK
        		});
        	}else{
        		Ext.MessageBox.show({
        			title: 'Mensaje del Sistema',
        			msg: operation.getError(),
        			icon: Ext.MessageBox.ERROR,
        			buttons: Ext.Msg.OK
        		});
        	}
        }else{
        	var json = Ext.decode(request.responseText);
        	Ext.MessageBox.show({
        		title: 'Mensaje del Sistema',
        		msg: json.message,
        		icon: Ext.MessageBox.ERROR,
        		buttons: Ext.Msg.OK
        	});
        }
    }

});