/*
 * File: app/view/clsLogin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeProduccion.view.clsLogin', {
    extend: 'Ext.window.Window',
    alias: 'widget.WindowLogin',

    requires: [
        'signeProduccion.view.undefinedViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'WindowLogin'
    },
    autoShow: true,
    height: 228,
    hidden: false,
    id: 'WindowLogin',
    resizable: false,
    width: 462,
    layout: 'anchor',
    closable: false,
    title: 'Autenticación de usuario',
    expandOnShow: false,
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'panel',
                    height: 45,
                    html: '<img src="./app/images/signe_logo.png" style="max-height:70%; max-width:70%;"/>',
                    width: 612,
                    layout: 'absolute',
                    title: ''
                },
                {
                    xtype: 'fieldset',
                    formBind: false,
                    title: 'Datos de identificación',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'usuario',
                            fieldLabel: 'Usuario',
                            msgTarget: 'side',
                            inputType: 'email',
                            allowBlank: false,
                            blankText: 'Este campo es obligatorio',
                            validateBlank: true,
                            vtype: 'email',
                            vtypeText: 'Este campo debe ser una cuenta de correo electrónico en formato "usuario@ejemplo.com"\'',
                            listeners: {
                                afterrender: 'onUsuarioAfterRender'
                            }
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'pass',
                            fieldLabel: 'Contraseña',
                            msgTarget: 'side',
                            inputType: 'password',
                            allowBlank: false,
                            blankText: 'Este campo es obligatorio',
                            validateBlank: true,
                            listeners: {
                                specialkey: 'onPassSpecialkey'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: '',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnIngreso',
                            width: 150,
                            scale: 'medium',
                            text: 'Ingresar',
                            tooltip: 'Ingresar al sistema.'
                        }
                    ]
                }
            ]
        }
    ],

    onUsuarioAfterRender: function(component, eOpts) {
        Ext.defer(function() {
            component.focus(true, 100);
        }, 1);

    },

    onPassSpecialkey: function(field, e, eOpts) {
        if (e.getKey() == e.ENTER){
        	var submitBtn = field.up('form').down('button#btnIngreso');
        	submitBtn.fireEvent('click', submitBtn, e);
        }
    }

});