/*
 * File: app/view/editarSistemaMedida.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeProduccion.view.editarSistemaMedida', {
    extend: 'Ext.window.Window',
    alias: 'widget.editarsistemamedida',

    requires: [
        'signeProduccion.view.undefinedViewModel1',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'editarformulario'
    },
    autoShow: true,
    height: 174,
    itemId: 'editarFormulario',
    width: 520,
    title: 'Sistemas de medida',
    modal: true,

    items: [
        {
            xtype: 'form',
            height: 445,
            width: 515,
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Formulario',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Descripción',
                            name: 'descripcion',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            blankText: 'Este campo es obligatorio.',
                            validateBlank: true
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnGuardarSistemaMedida',
                            icon: '',
                            iconCls: 'icon-save',
                            scale: 'medium',
                            text: 'Guardar'
                        }
                    ]
                }
            ]
        }
    ]

});