/*
 * File: app/view/escritorio.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeProduccion.view.escritorio', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.escritorioPrincipal',

    requires: [
        'signeProduccion.view.escritorioViewModel',
        'signeProduccion.view.menuView',
        'signeProduccion.view.listaSistemaMedida',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'escritorio'
    },
    id: 'escritorioPrincipal',
    itemId: '',

    layout: {
        type: 'border',
        padding: '10 10 10'
    },
    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            id: 'contenedorMenu',
            margin: '0 0 5 0',
            width: 350,
            layout: 'card',
            collapseDirection: 'left',
            collapsible: true,
            hideCollapseTool: true,
            titleCollapse: true,
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'top',
                    height: 60,
                    html: '<div class="logo-empresa"></div>',
                    itemId: 'panelLogo'
                }
            ],
            items: [
                {
                    xtype: 'menuview'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 100,
            region: 'center',
            split: false,
            id: 'contenedorMantenimiento',
            margin: '0 0 5 0',
            layout: 'card',
            items: [
                {
                    xtype: 'listasistemamedida'
                }
            ]
        },
        {
            xtype: 'container',
            region: 'south',
            height: 30,
            id: 'contenedorEstado',
            layout: 'card',
            items: [
                {
                    xtype: 'toolbar',
                    border: 1,
                    height: 30,
                    id: 'statusBar',
                    items: [
                        {
                            xtype: 'label',
                            id: 'lblUsuario'
                        },
                        {
                            xtype: 'label',
                            id: 'lblSucursal'
                        }
                    ]
                }
            ]
        }
    ]

});