/*
 * File: app/view/menuView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeProduccion.view.menuView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.menuview',

    requires: [
        'signeProduccion.view.menuViewViewModel',
        'Ext.view.View',
        'Ext.XTemplate',
        'Ext.panel.Tool'
    ],

    viewModel: {
        type: 'menuview'
    },
    height: 667,
    id: 'images-view',
    width: 350,
    bodyStyle: 'background-color:#2f7d9c !important;',
    title: 'Menu',

    items: [
        {
            xtype: 'dataview',
            itemId: 'myview',
            itemSelector: 'div.menu-contenedor',
            itemTpl: [
                '<tpl for=".">',
                '<div class="menu-contenedor">',
                '    ',
                '    <div class="menu-thumb"><img src="./app/packages/build/resources/imagenmenu/{thumb}" />',
                '    </div>',
                '    <div class="menu-contenido">',
                '    <h3 class="menu-titulo">{name:htmlEncode}</h3>',
                '        <p class= "menu-descripcion">{description:htmlEncode}</p>',
                '  </div>',
                '</div>',
                '	',
                '</tpl>'
            ],
            overItemCls: 'x-item-over',
            store: 'storeMenu'
        }
    ],
    tools: [
        {
            xtype: 'tool',
            id: 'toolCerrarMenuPrincipal'
        }
    ]

});