/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'modelSistemaMedida',
        'modelLogin',
        'modelMenu'
    ],
    stores: [
        'storeSistemaMedida',
        'storeLogin'
    ],
    views: [
        'listaSistemaMedida',
        'editarSistemaMedida',
        'clsLogin',
        'escritorio',
        'menuView'
    ],
    controllers: [
        'controladorLogin',
        'controladorEscritorio'
    ],
    name: 'signeProduccion',

    launch: function() {
        Ext.create('signeProduccion.view.clsLogin', {renderTo: Ext.getBody()});
        localStorage.removeItem('nombre-usuario');
        localStorage.removeItem('signeProduccion-token');

        signeProduccion.app.getController('controladorSistemaMedida').cargarSistemaMedida();

        //var token = "dfdfdfdf";

    },

    salirSistema: function() {
        localStorage.removeItem('nombre-usuario');
        localStorage.removeItem('signeProduccion-token');

        var windowLogin= Ext.widget('WindowLogin');
        windowLogin.show();

    }

});
