/*
 * File: app/controller/controladorLogin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeProduccion.controller.controladorLogin', {
    extend: 'Ext.app.Controller',

    stores: [
        'storeLogin',
        'storeMenu'
    ],

    control: {
        "#btnIngreso": {
            click: 'onButtonClickIngresar'
        },
        "#toolSalir": {
            click: 'onToolClickSalir'
        }
    },

    onButtonClickIngresar: function(button, e, eOpts) {
        var win = button.up('window');
        form = win.down('form');

        if (form.getForm().isValid()) {
            var user = "'" + form.down('#usuario').getValue() + "'";
            var pwd = "'" + form.down('#pass').getValue() + "'";




            store = this.getStoreLoginStore();

            var lparametros = Ext.util.JSON.encode({"user":user,"pwd":pwd,"empresa":1});
            store.getProxy().setExtraParam("listparams", lparametros);

            storeMenu = this.getStoreMenuStore();

            store.load(function(records, operation, success) {
                if(this.getCount()>=1){

                    indice = store.getAt(0);


                    if (indice.get("token")){

                        localStorage.setItem('nombre-usuario', indice.get('nombre') + ' ' + indice.get('apellido'));

                        localStorage.setItem('signeProduccion-token', indice.get("token"));

                        win.close();

                        // Carga las opciones del menu principal
                        storeMenu.getProxy().setExtraParam("id", 5);

                        var lparametros = Ext.util.JSON.encode({"empresa":1});
                        storeMenu.getProxy().setExtraParam("listparams", lparametros);

                        storeMenu.load();
                        //

                        var escritorio= Ext.widget('escritorioPrincipal');
                        escritorio.show();

                        statusBar = escritorio.down('#statusBar');
                        statusBar.items.getAt(0).update('Usuario: ' + localStorage.getItem('nombre-usuario'));

                    }
                }
                else{

                    localStorage.removeItem('signeProduccion-token');

                    Ext.MessageBox.show({
                        title: 'Mensaje del Sistema',
                        msg: 'Los datos de usuario que se proporcionarón son inválidos.',
                        icon: Ext.MessageBox.ERROR,
                        buttons: Ext.Msg.OK
                    });
                }
            });

        }
    },

    onToolClickSalir: function(tool, e, owner, eOpts) {

    }

});
