/*
 * File: app/controller/controladorSistemaMedida.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeProduccion.controller.controladorSistemaMedida', {
    extend: 'Ext.app.Controller',

    stores: [
        'storeSistemaMedida'
    ],

    refs: {
        listaSistemaMedida: '#listaSistemaMedida'
    },

    control: {
        "#btnAniadirSistemaMedida": {
            click: 'onBtnAniadirSistemaMedidaClick'
        },
        "#btnEditarSistemaMedida": {
            click: 'onBtnEditarSistemaMedidaClick'
        },
        "#btnEliminarSistemaMedida": {
            click: 'onBtnEliminarSistemaMedidaClick'
        },
        "#btnGuardarSistemaMedida": {
            click: 'onBtnGuardarSistemaMedidaClick'
        },
        "#listaSistemaMedida": {
            itemdblclick: 'onListaSistemaMedidaItemDblClick'
        }
    },

    onBtnAniadirSistemaMedidaClick: function(button, e, eOpts) {
        var view = Ext.widget('editarsistemamedida');
    },

    onBtnEditarSistemaMedidaClick: function(button, e, eOpts) {
        this.editarSistemaMedida();
    },

    onBtnEliminarSistemaMedidaClick: function(button, e, eOpts) {
        record = this.getListaSistemaMedida().getSelectionModel().getSelection();

        if(record.length > 0){
            store = this.getStoreSistemaMedidaStore();

            //store.getProxy().setExtraParam("idmod",signeApp.app.idmodapp);
            var lparametros = Ext.util.JSON.encode({"empresa":1});
            store.getProxy().setExtraParam("listparams", lparametros);


            Ext.MessageBox.show({
                title : 'Eliminar Registro',
                buttons : Ext.MessageBox.YESNO,
                msg : 'Realmente desea eliminar el sistema : '+record[0].data.descripcion+' ?',
                icon : Ext.Msg.WARNING,
                fn : function(btn)
                {
                    if (btn == 'yes')
                    {
                        store.remove(record);

                    }
                }
            });
        }else{
            Ext.MessageBox.show({
                title: 'Mensaje del Sistema',
                msg: 'Por favor seleccione el formulario que desea eliminar.',
                icon: Ext.MessageBox.ERROR,
                buttons: Ext.Msg.OK
            });
        }
    },

    onBtnGuardarSistemaMedidaClick: function(button, e, eOpts) {


        var win = button.up('window'),
        	form = win.down('form'),
        	record = form.getRecord(),
        	values = form.getValues();

        // Unicamente modificar el nombre del store en este evento //
        var store = this.getStoreSistemaMedidaStore();

        var token = localStorage.getItem('signeProduccion-token');

        store.getProxy().setHeaders({
            Authorization:'Bearer ' + token
        });

        var lparametros = Ext.util.JSON.encode({"empresa":1});
        store.getProxy().setExtraParam("listparams", lparametros);
        //

        if (form.getForm().isValid()){
        	if (record){
        		record.set(values);
        	}
        	else{
        		store.add(values);
        	}
        	win.close();
        }


    },

    onListaSistemaMedidaItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.editarSistemaMedida();
    },

    cargarSistemaMedida: function() {
        var store = this.getStoreSistemaMedidaStore();

        var token = localStorage.getItem('signeProduccion-token');

        store.getProxy().setHeaders({
            Authorization:'Bearer ' + token
        });


        var lparametros = Ext.util.JSON.encode({"empresa":1});
        store.getProxy().setExtraParam("listparams", lparametros);

        store.load();
    },

    editarSistemaMedida: function() {
        var record= this.getListaSistemaMedida().getSelectionModel().getSelection();
        if(record.length > 0){
        	var view = Ext.widget('editarsistemamedida');
        	var EditForm=view.down('form');
        	EditForm.loadRecord(record[0]);
        }else{
        	Ext.MessageBox.show({
        		title: 'Mensaje del Sistema',
        		msg: 'Por favor seleccione el registro que desea editar.',
        		icon: Ext.MessageBox.ERROR,
        		buttons: Ext.Msg.OK
        	});
        }
    }

});
